# Generated by Django 5.0.3 on 2024-04-21 06:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataGather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagather',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='اگر به تصاویر ژئوتگ دسترسی ندارید می\u200cتوانید نقطه مورد نظر را در نقشه پیداکنید. مسئولیت اخلاقی و وجدانی اطلاعات اشتباه بر عهده شماست'),
        ),
    ]
