# Generated by Django 5.0.3 on 2024-04-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataGather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagather',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
